kind: Deployment
apiVersion: apps/v1
metadata:
  name: longtail-log-pipeline
spec:
  selector: 
    matchLabels: 
      app: longtail-log-pipeline 
  template:
    metadata:
      labels:
        app: longtail-log-pipeline
    spec:
      hostname: longtail-log-pipeline
      containers:
      - name: longtail-log-pipeline
        ports:
          - containerPort: 5044
            name: filebeat
          - containerPort: 9600
            name: logstash
        image: docker.elastic.co/logstash/logstash:7.16.2
        volumeMounts:
        - name: longtail-log-pipeline-config
          mountPath: /usr/share/logstash/pipeline/
        command:
        - logstash
      volumes:
      - name: longtail-log-pipeline-config
        configMap:
          name: longtail-log-pipeline
          items:
          - key: longtail-log-es.conf
            path: longtail-log-es.conf
--- 
kind: Service
apiVersion: v1
metadata:
  name: longtail-log-pipeline
spec:
  type: NodePort
  selector:
    app: longtail-log-pipeline
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    nodePort: 30103
    name: filebeat
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash

